version: "3.4"

services:
  web:
    build:
      context: .
      args:
        BUILD_ENV: "development"
    command: "/usr/local/src/iclick-app/bin/start"
    env_file:
      - ./.env
    environment:
      REACTION_APP_NAME: "iclick-front.web"
    ports:
      - 4000:4000
    volumes:
      #      - $HOME/.cache/yarn-offline-mirror:/home/node/.cache/yarn-offline-mirror
      - web-yarn:/home/node/.cache/yarn
      - .:/usr/local/src/iclick-app
      - empty_node_modules:/usr/local/src/iclick-app/node_modules # do not link node_modules in, and persist it between dc up runs
      - node_modules:/usr/local/src/node_modules

volumes:
  web-yarn:
  empty_node_modules:
  node_modules:
